### ISSUE TITLE
Error 500 with Single Sign On extension

### ISSUE THREAD

**Issue by antoinebidault** [gwillem/freeflarum.com#267]
__Describe the bug:__
I am having a 500 error when trying to trigger a SSO request using the SSO extension in my flarum.
When I'm doing  a request to https://dastracommunity.freeflarum.com/api/sso/jwt with an authorization Bearer token set.
I've tried on a local flarum installation and it worked. This is why I think this issue is related to freeflarum.

__My FreeFlarum forum URL:__
https://dastracommunity.freeflarum.com

**To Reproduce:**

1. Activate the Single-Sign On plugin
2. I've configured the JWT feature as following :
![image](https://user-images.githubusercontent.com/7562672/133160763-f07fe475-c082-4c96-8321-0a46e8fee7f2.png)

3. Then, i try to execute this kind of command in order to trigger SSO : 
```CURL
curl --location --request GET 'https://dastracommunity.freeflarum.com/api/sso/jwt' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiYXVkIjoiaHR0cHM6Ly9kYXN0cmFjb21tdW5pdHkuZnJlZWZsYXJ1bS5jb20iLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjIsImF0dHJpYnV0ZXMiOnsiZW1haWwiOiJqb2huZG9lQGdpdGh1Yi5jb20iLCJ1c2VybmFtZSI6ImpvaG5kb2UifX0.x4gQzGYOyfAgyraKzOuh7jTZkS_Fnqv95ucnkUJHLiQ'
```
You can issue your own JWT token using  [this link](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZXN0LmdpdGh1Yi5jb20iLCJpYXQiOjE2MzE1Njc5MjksImV4cCI6MTYzMTY1NDMyOSwic3ViIjoiMTAyNiIsInVzZXIiOnsiaWQiOiIxMDI2IiwiYXR0cmlidXRlcyI6eyJlbWFpbCI6ImpvaG5kb2VAZ2l0aHViLmNvbSIsInVzZXJuYW1lIjoiam9obmRvZUBnaXRodWIuY29tIiwiaXNFbWFpbENvbmZpcm1lZCI6dHJ1ZSwiYXZhdGFyVXJsIjpudWxsfX19.fcopDSWfpRvmOiipZZwP-aXRRa7dzId5ECXxgaILAl4)

4. The server return an unknown error
```JSON
{
    "errors": [
        {
            "status": "500",
            "code": "unknown"
        }
    ]
}
```

I am having the following error in the log files, it seems like a library (Lcobucci\JWT) is missing in the freeflarum instance : 
```
[2021-09-12 19:26:54] flarum.ERROR: Error: Class "Lcobucci\JWT\Signer\Hmac\Sha256" not found in /app/vendor/maicol07/flarum-ext-sso/src/JWTSSOController.php:100
Stack trace:
#0 /app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Maicol07\SSO\JWTSSOController->handle()
#1 /app/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#2 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process()
#3 /app/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#4 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\ThrottleApi->process()
#5 /app/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#6 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process()
#7 /app/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#8 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process()
#9 /app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#10 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process()
#11 /app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(56): Laminas\Stratigility\Next->handle()
#12 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#13 /app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#14 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process()
#15 /app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#16 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process()
#17 /app/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#18 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process()
#19 /app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#20 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\FakeHttpMethods->process()
#21 /app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#22 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process()
#23 /app/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#24 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process()
#25 /app/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#26 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process()
#27 /app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#28 /app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#29 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process()
#30 /app/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#31 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process()
#32 /app/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#33 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process()
#34 /app/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#35 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process()
#36 /app/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#37 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process()
#38 /app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#39 /app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#40 /app/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#41 /app/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#42 /app/public/index.php(22): Flarum\Http\Server->listen()
#43 {main}  
```
Here is the extension file that is related to this issue : 
https://github.com/maicol07/flarum-ext-sso/blob/master/src/JWTSSOController.php

**Expected behavior:**
Even if the given token is invalid, it must return at least a 400 error

Hope it helps / Thanks a lot for maintaining this great service !

**Comment by CWKevo** [comment]
Great report! I've installed the missing `lcobucci/jwt` for all FreeFlarum forums. Could you try again to see whether or not it works this time please?

**Comment by antoinebidault** [comment]
Great ! The endpoint is responding a 200 code with an authentication token.
Thanks a lot for the quick reply !

**Comment by CWKevo** [comment]
No problem, closing this now
